Fix build for missing last_modified_at tag
BonnyCI/bonnyci.org pull request #29
Opened 2017-02-18 00:13 UTC by SpamapS

I was mistaken thinking this plugin was available in GH pages, but it is
not.

2017-02-18 00:15 UTC, anne-bonny commented
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/bonnyci.org/29/1487376795.71/bonnyci-run-check : FAILURE in 2m 16s

2017-02-20 15:42 UTC, mlangbehn requested changes

2017-02-20 15:42 UTC, mlangbehn commented on beta/README.md
> +via Twitter: @SpamapS, or email [clint at fewbar dot com](mailto:clint at fewbar dot com)*
Trailing asterix.

2017-02-20 15:50 UTC, mlangbehn approved these changes
Looks good to me.

2017-02-20 15:50 UTC, mlangbehn commented on beta/README.md
> +via Twitter: @SpamapS, or email [clint at fewbar dot com](mailto:clint at fewbar dot com)*
^ Please disregard. I missed the opening asterix on 188. ^

2017-02-20 15:52 UTC, merged