Fix floating ip quota in network-design.md
BonnyCI/bonnyci.org pull request #36
Opened 2017-02-22 15:43 UTC by eggshell

Initially, the floating ip quota is said to be 30, then 50 a little
further down. Since we have a /27 subnet, I assume 50 is a typo and
we only have 30 usable addresses.

Signed-off-by: Cullen Taylor <cullentaylor@outlook.com>

2017-02-22 18:10 UTC, omgjlk requested changes
Well, it's more nuanced than that. Additional subnets could be added at any time, however the quota per-project is still set at 50. 50 is just a Neutron default quota, and changing it is ... difficult, so it remains at 50, even though we do not have 50 usable.

How we explain that, I don't know.

2017-03-27 19:51 UTC, j2sol commented
I think the wording is pretty fine. The subtle difference between "quota" and the ranges we pay for is probably not important.

However, we did recently add a second range of floating addresses, `169.44.161.32/27`. We need to account for this range in the doc.

2017-03-28 21:18 UTC, eggshell commented
@j2sol updated.

2017-03-28 21:31 UTC, omgjlk approved these changes

2017-03-28 21:34 UTC, merged