Network design v2 changes: One bastion, Two Zuuls
BonnyCI/bonnyci.org pull request #49
Opened 2017-03-22 20:08 UTC by gandelman-a

This proposes some changes to allow a single bastion to manage
multiple Zuul environments.

Related-Issue: BonnyCI/projman#139

Signed-off-by: Adam Gandelman <adamg@ubuntu.com>

2017-03-22 20:10 UTC, anne-bonny commented
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/bonnyci.org/49/1490213293.89/bonnyci-run-check : FAILURE in 2m 34s

2017-03-22 23:05 UTC, anne-bonny commented
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/bonnyci.org/49/1490223760.41/bonnyci-run-check : FAILURE in 2m 19s

2017-03-23 17:04 UTC, mlangbehn commented on lore/developers/contributing/designs/network-design-v2.md
> +
Please remove this extra new line.

2017-03-23 17:04 UTC, mlangbehn commented on lore/developers/contributing/designs/network-design-v2.md
> +The original network topology was designed to be a 2 tier setup where the control-plane network hosted all service hosts and the head bastion, and the nodepool network hosted all nodepool slaves.  Th
There's been a push to make all Markdown files have line breaks at 80 characters. Please update accordingly.

2017-03-23 17:04 UTC, mlangbehn commented on lore/developers/contributing/designs/network-design-v2.md
> +The current bastion will be removed from the current ``control-plane`` network and put on its own common network (``common-network``), with its own CIDR. The existing router (``bonnyci-router``) rout
Markdown only requires one set of backticks for inline code.

2017-03-23 21:59 UTC, anne-bonny commented
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/bonnyci.org/49/1490306199.91/bonnyci-run-check : FAILURE in 2m 22s

2017-03-27 18:04 UTC, gandelman-a commented on lore/developers/contributing/designs/network-design-v2.md
> +* Adding new ansible inventory for the new environment, updating the bastion playbook to deploy a new ansible-runner task for the new environment.
So these list items need to not get wrapped at 80, otherwise they cause linting errors.

2017-03-31 14:39 UTC, mlangbehn submitted a review, later dismissed

2017-03-31 14:39 UTC, mlangbehn commented on lore/developers/contributing/designs/network-design-v2.md
> +* Adding new ansible inventory for the new environment, updating the bastion playbook to deploy a new ansible-runner task for the new environment.
In order to wrap lines in a list, you must indent them to the same level. See [this section](https://github.com/mivok/markdownlint/blob/master/docs/RULES.md#md032---lists-should-be-surrounded-by-blank-lines) of the markdownlint documentation for clarification.

2017-04-03 19:32 UTC, mlangbehn reviewed
Looks good to me now, but someone else should take a look, too.

2017-04-04 20:46 UTC, omgjlk requested changes
I like it, but there is one typo to fix. I'd also like to see at least one other person review the sanity.

2017-04-04 20:46 UTC, j2sol commented on lore/developers/contributing/designs/network-design-v2.md
> +existing router (`bonnyci-router`) router will receive a network interface on
`router` is repeated here.

2017-04-17 18:20 UTC, anne-bonny commented
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/bonnyci.org/49/1492453069.7/bonnyci-run-check : FAILURE in 2m 27s

2017-04-17 18:41 UTC, mlangbehn approved these changes
Looks good to me.

2017-04-17 18:42 UTC, omgjlk approved these changes

2017-04-17 20:08 UTC, gandelman-a commented
gate-recheck

2017-04-17 20:11 UTC, merged