Add note about multiple CI services to use lore
BonnyCI/bonnyci.org pull request #58
Opened 2017-04-11 21:05 UTC by eggshell

Having multiple CI services test a repository can cause errant
merge failures with BonnyCI, so we should add a note to the
lore which describes this.

Signed-off-by: Cullen Taylor <cullentaylor@outlook.com>

2017-04-11 21:30 UTC, mlangbehn submitted a review, later dismissed
Two nits and a question inline.

2017-04-11 21:30 UTC, mlangbehn commented on lore/end_users/use/README.md
> +ex: a repository which has both BonnyCI and TravisCI) will encounter merge
`TravisCI` should be `Travis CI`.

2017-04-11 21:30 UTC, mlangbehn commented on lore/end_users/use/README.md
> +**NOTE**: Repositories which require multiple continuous integration checks (
Looks like there is an extra space at the end of this line? If not, the newline is causing a space to be rendered. See the [rendered file][1] for what I mean.

[1]:https://github.com/eggshell/eggshell.github.io/blob/03fc84f54da58a651c015eb977f4fec154316391/lore/end_users/use/README.md#competing-pull-requests

2017-04-11 21:30 UTC, mlangbehn commented on lore/end_users/use/README.md
> +with BonnyCI is discouraged.
Should we suggest a hack to make this work? Or maybe open an issue to address this case?

2017-04-11 21:38 UTC, eggshell commented on lore/end_users/use/README.md
> +with BonnyCI is discouraged.
@mlangbehn I'm not aware of any currently existing hacks, but I'll open an issue to address this.

2017-04-11 21:38 UTC, eggshell commented on lore/end_users/use/README.md
> +ex: a repository which has both BonnyCI and TravisCI) will encounter merge
@mlangbehn done, thanks.

2017-04-11 21:38 UTC, eggshell commented on lore/end_users/use/README.md
> +**NOTE**: Repositories which require multiple continuous integration checks (
@mlangbehn done, thanks

2017-04-11 22:29 UTC, ConsoleCatzirl reviewed
:+1: LGTM

2017-04-11 23:18 UTC, omgjlk requested changes

2017-04-11 23:18 UTC, j2sol commented on lore/end_users/use/README.md
> +with BonnyCI is discouraged.
So.... this is not quite true.

One can use multiple CI services alongside BonnyCI. That itself is not ht problem. What _is_ a problem is if in Branch Protection settings, the repository requires successful checks from CI systems other than BonnyCI. That is what will cause the merge failures.

Adding a CI system and requiring it be passing for merges are two separate steps.

2017-04-12 00:03 UTC, eggshell commented on lore/end_users/use/README.md
> +with BonnyCI is discouraged.
@j2sol thanks for the clarification (this stemmed from a rec in IRC). I updated this PR accordingly.

2017-04-14 19:16 UTC, omgjlk approved these changes

2017-04-14 19:31 UTC, merged